@startuml Assignment 1 class diagram
class PeerDetails {
    - address: String
    - port: int
    
    + getPort(): int
}

class PeerDictionary {
    - data: HashMap
    - blacklist: Array<String>

    + get(): PeerDetails
    + set(): void
    + deleteAndBlacklist(): void
}

PeerDictionary *-- PeerDetails

class PeerSearcher {
    - peerDict: PeerDictionary

    + run(): void
    - discoverPeers(): void
    - savePeers(): void
    - getDiscoverMessage(): String
}

class PeerDiscoveryServer {
    - repoId: String
    - repoServerPort: int
    - socket: DatagramSocket
    
    - reply(): void
    - buildPeerDiscoveryResponse(): String
}

class PeerDiscoveryProtocol {
    {static} BROADCAST_PORT: int
    - repoId: String
    - repoServerPort: int

    + start(): void
    + getPeerDict(): PeerDictionary
}

PeerDiscoveryProtocol -- PeerDiscoveryServer
PeerDiscoveryProtocol -- PeerSearcher

class Repository {
    - data: HashMap

    + set(): void
    + add(): void
    + get(): List<Integer>
    + delete(): void
    + sum(): Integer
    + avg(): Double
    + min(): Integer
    + max(): Integer
    + getSize(): Integer

}

class SocketList {
    - list: ArrayList

    + add(): void
    ' TODO: Need this?
    - close(): void
}

class RepositoryProtocol {
    - s: Socket
    - scanner: Scanner
    - writer: PrintWriter
    - repo: Repository

    + run(): void
    - breakdownCommandKey(): String[]
    - handleRemoteCommand(): void
    - remoteGet(): int
    - sendln(): void
    - recvln(): String
    - close(): void
    - isConnected(): boolean
}

class RemoteCallHandler {
    - scanner: Scanner
    - writer: PrintWriter
    - s: Socket

    - sendln(): void
    - recvln(): String
    - runCommand(): String
}

RepositoryProtocol -- RemoteCallHandler

class CustomPair{
    - p1: int
    - p2: int

    + getP1(): int
    + getP2(): int
    + addToP1(): void
    + addToP2(): void
}

RepositoryProtocol -- CustomPair

class MainThreadHandler {
    - stop: boolean
    + run(): void
}

MainThreadHandler -- RepositoryProtocol

class RepositoryServer {
    - repoID: String
    - repo: Repository
    - sockList: SocketList
    - sc: ServerSocket
 
    + start(): void
    + stop(): void
    + getPort(): int
}

RepositoryServer -- PeerDiscoveryProtocol
RepositoryServer -- PeerDictionary
RepositoryServer -- Repository
RepositoryServer -- SocketList
RepositoryServer -- MainThreadHandler

class Logger {
    - {static} logger: Logger
    - out: PrintStream

    + {static} getInstance(): Logger
    + reportError: void
    + log: void
}

@enduml

